service: checkly-cli-in-aws-lambda
frameworkVersion: '3'

plugins:
  - serverless-offline
  
provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
